name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      - name: Docker Hub Login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_ID }}' --password-stdin
  
      - name: Test
        run: |
          docker build -t meirkell/react-test -f ./client/Dockerfile.dev ./client
          docker run meirkell/react-test npm test -- --coverage --watchAll=false
      - name: Build Docker Images
        run: |
          docker build -t meirkell/multi-client ./client
          docker build -t meirkell/multi-nginx ./nginx
          docker build -t meirkell/multi-server ./server
          docker build -t meirkell/multi-worker ./worker
          docker push meirkell/multi-client
          docker push meirkell/multi-nginx
          docker push meirkell/multi-server
          docker push meirkell/multi-worker
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' '**node_modules**'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip